### ISSUE TITLE
Default-setting for DoNotAddEqualityOperators

### ISSUE THREAD

**Issue by greuelpirat** [Fody/Equals#113]
Please add the possibility to set default for `[Equals(DoNotAddEqualityOperators = true)]` in the `FodyWeavers.xml` like 

```
<?xml version="1.0" encoding="utf-8"?>
<Weavers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FodyWeavers.xsd">
    <Equals DoNotAddEqualityOperators="true" />
</Weavers>
```

**Comment by SimonCropp** [comment]
Can u follow the issue template https://github.com/Fody/.github/blob/master/.github/ISSUE_TEMPLATE/feature_proposal.md
