### ISSUE TITLE
Calls within defining library do not honor interface

### ISSUE THREAD

**Issue by ndrwrbgs** [Fody/Equals#118]
#### Preamble

 * Fody 6.0.0
 * Equals.Fody 4.0.0
 * MSBuild 16

#### Describe the issue

When a modified type is used within the library, calls with that type are not rewritten honoring the interface. It's not a major problem for those well versed in Fody, but for another developer coming along and learning it would be unexpected.

#### Minimal Repro
FodyWeavers.xml packages.config, and csproj excluded. Was targeting .NET 4.6.2

Program.cs
```C#
using System;

namespace DelMe.FodyEquals
{
    using LibraryThatUsesEquatableAtCompileTime;

    class Program
    {
        static void Main(string[] args)
        {
            if (new TypeUnderTest() is IEquatable<TypeUnderTest>)
            {
                Console.WriteLine("It is indeed equatable");
            }
            EquatableUser.DoSomething(new TypeUnderTest());
        }
    }

    [Equals]
    class TypeUnderTest
    {
        public int Number { get; private set; }

        public static bool operator ==(TypeUnderTest left, TypeUnderTest right) => Operator.Weave(left, right);
        public static bool operator !=(TypeUnderTest left, TypeUnderTest right) => Operator.Weave(left, right);
    }
}
``` 

Class1.cs
```C#
using System;

namespace LibraryThatUsesEquatableAtCompileTime
{
    public static class EquatableUser
    {
        public static void DoSomething(object obj)
        {
            throw new NotImplementedException("We want it to be always used as IEquatable");
        }

        // For additional testing, since determining between this and the other method might be ambiguous
        //public static void DoSomething<T>(IEquatable<T> equatable)
        //{
            //throw new NotImplementedException("We expect the most specific method to be used, normal code would use the below method");
        //}

        public static void DoSomething<T>(T item)
            where T : IEquatable<T>
        {

        }
    }
}
```

#### Make an effort to fix the bug
Feel free to assign to me if you feel strongly about the effort rule and I'll add it to my backlog :)

**Comment by ndrwrbgs** [comment]
The easy solution would be requiring the callers to do everything like the == approach, to add IEquatable<T> (but with dummy methods) that we replace.

The harder (but nicer consumption) solution would be to replace such calls within the library where they are found.

**Comment by ltrzesniewski** [comment]
Interesting. I suppose this is only a problem if you build both projects in the same solution.

If you provide Project1 in a different way, like a NuGet package, the compiler will see that `TypeUnderTest` implements `IEquatable`.

I thought that Fody should be able to do its job before the compiler reads the Project1 metadata when compiling Library2.

**Comment by ndrwrbgs** [comment]
_Updating example to make it clear the separate libraries aren't actually needed_

**Comment by ltrzesniewski** [comment]
Note that the "harder solution" won't be possible to implement correctly for all cases.

You'd have to reimplement Roslyn's overload resolution (which is a major pain point in the compiler already), while having *less* information about the code. For instance, you wouldn't be able to detect when a user forces a particular overload with `EquatableUser.DoSomething((object)new TypeUnderTest());` as that explicit `(object)` cast is made implicit in IL. And that's only one example of a problem, there are more.

Adding a dummy `IEquatable<T>` implementation is the better approach.

**Comment by ndrwrbgs** [comment]
Do the participants here think we should add those dummy methods similar to the == we added, or omit and leave as it stands today? If we are going ahead with it, I can take on making the PR since I brought up the issue (assign something to me please :) )

**Comment by tom-englert** [comment]
@ndrwrbgs still interested in changing this? 
IMO equality is a perfect candidate for a Roslyn source generator like e.g. this: https://github.com/diegofrata/Generator.Equals, this will not have such side effects.
