### ISSUE TITLE
Arrays are compared by reference

### ISSUE THREAD

**Issue by johnsparrowuk** [Fody/Equals#14]
If the class contains an array eg `public int[] Numbers { get; set; }` the EqualsInternal method just contains 

```
return left.Numbers == right.Numbers;
```

Your IsCollection method doesn't seem to recognise plain arrays, although if I use `IList<int>` it works and generates:

```
return ((left != null) ? (right != null && Helpers.CollectionEquals(left.Numbers, right.Numbers)) : (right == null));
```

.NET 4.5.2 (Windows)

**Comment by rjasica** [comment]
Thanks for reporting this!
I fixed this bug in version 1.4
