### ISSUE TITLE
Equals.Fody doesn't play nicely with PostSharp

### ISSUE THREAD

**Issue by jasonwoods-7** [Fody/Equals#16]
Steps to recreate issue:

1. Create a new dll project.
2. Go into package manager console and add Equals.Fody and PostSharp.
3. Add an empty class and add the Equals attribute to the class.
4. Compile.

PostSharp throws an PostSharp.Sdk.AssertFailedException during the build.

**Comment by SimonCropp** [comment]
suggest u raise this as a bug in postsharp

**Comment by jasonwoods-7** [comment]
Fair enough.  Here's the link to the issue I submitted in case you're interested in following it: http://support.sharpcrafters.com/discussions/problems/2667-exception-thrown-during-compilation-when-using-equalsfody

**Comment by SimonCropp** [comment]
@jasonwoods-7 thanks

**Comment by SimonCropp** [comment]
@jasonwoods-7 ok i checked the repro u uploaded to postsharp. fody is producing valid IL so it looks like a bug on the postsharp side. I would post this in the postsharp form but their forum is blocking me with captchas even though i am logged in.
