### ISSUE TITLE
add simon to nuget

### ISSUE THREAD

**Issue by SimonCropp** [Fody/Equals#19]
@rjasica can u add me to nuget?

**Comment by rjasica** [comment]
Is "simon" your account name on nuget.org?
I had tried, but nuget reported error: "Sorry, simon hasn't verified their email account yet and we cannot proceed with the request."

**Comment by SimonCropp** [comment]
this is me http://nuget.org/profiles/simoncropp

**Comment by rjasica** [comment]
I added you to owners
