### ISSUE TITLE
Mono.Cecil Exception in classes that contains IList / ICollection properties in abstract base class

### ISSUE THREAD

**Issue by emilianopenedo** [Fody/Equals#20]
Fody: An unhandled exception occurred:

    Exception:
    Member 'System.Collections.Generic.ICollection1' is declared in another module and needs to be imported StackTrace: at Mono.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider) at Mono.Cecil.SignatureWriter.WriteTypeSignature(TypeReference type) at Mono.Cecil.SignatureWriter.WriteMethodSignature(IMethodSignature method) at Mono.Cecil.MetadataBuilder.GetMemberRefSignature(MemberReference member) at Mono.Cecil.MetadataBuilder.CreateMemberRefRow(MemberReference member) at Mono.Cecil.MetadataBuilder.GetMemberRefToken(MemberReference member) at Mono.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider) at Mono.Cecil.Cil.CodeWriter.WriteOperand(Instruction instruction) at Mono.Cecil.Cil.CodeWriter.WriteInstructions() at Mono.Cecil.Cil.CodeWriter.WriteResolvedMethodBody(MethodDefinition method) at Mono.Cecil.Cil.CodeWriter.WriteMethodBody(MethodDefinition method) at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method) at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type) at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type) at Mono.Cecil.MetadataBuilder.AddTypeDefs() at Mono.Cecil.MetadataBuilder.BuildTypes() at Mono.Cecil.MetadataBuilder.BuildModule() at Mono.Cecil.ModuleWriter.<BuildMetadata>b__0(MetadataBuilder builder, MetadataReader _) at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func3 read)
    at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
    at Mono.Cecil.ModuleWriter.WriteModuleTo(ModuleDefinition module, Stream stream, WriterParameters parameters)
    at Mono.Cecil.ModuleDefinition.Write(Stream stream, WriterParameters parameters)
    at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
    at InnerWeaver.WriteModule() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\ModuleWriter.cs:line 18
    at InnerWeaver.Execute() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\InnerWeaver.cs:line 85
    Source:
    Mono.Cecil
    TargetSite:
    Mono.Cecil.MetadataToken LookupToken(Mono.Cecil.IMetadataTokenProvider)

**Comment by emilianopenedo** [comment]
I´ve isolated the issue to this code, an assembly referencing another where is located an abstract generic class.

// assembly1
namespace Assembly
{
    [Equals]
    public class Foo : Bar<int>
    {
        public int Prop { get; set; }
    }
}

// assembly2
namespace AssemblyReferenced
{
    public abstract class Bar<T>
    {
        protected Bar()
        {
            Collection = new Collection<Item>();
        }

        public ICollection<Item> Collection { get; set; }
    }

    public class Item
    {
    }
}

**Comment by rjasica** [comment]
Thnak you for reporting this bug. 
Fixed in 1.4.5

**Comment by emilianopenedo** [comment]
Thank you Rafal for supporting this plugin
