### ISSUE TITLE
GetHashCode should use unchecked arithmetic

### ISSUE THREAD

**Issue by drewnoakes** [Fody/Equals#21]
I've only read the README so apologies if this is invalid.

The generated `GetHashCode` is shown as:

```csharp
public override int GetHashCode()
{
    return this.X.GetHashCode() * 397 ^ this.Y.GetHashCode();
}
```

This arithmetic is almost certain to have integer overflow. If the assembly is compiled with 'checked' arithmetic, will this expression throw? If not (because non-checking IL is emitted) perhaps the README code should be updated to something like:

```csharp
public override int GetHashCode()
{
    return unchecked(this.X.GetHashCode() * 397 ^ this.Y.GetHashCode());
}
```

or

```csharp
public override int GetHashCode()
{
    unchecked
    {
        return this.X.GetHashCode() * 397 ^ this.Y.GetHashCode();
    }
}
```

**Comment by rjasica** [comment]
It doesn't matter if the assembly is compiled with 'checked'  or without the flag. The non-checking IL is alway emitted in the GetHashCode method.
I am going to update the readme.
