### ISSUE TITLE
Equals function should consider NotNullAttribute on fields/auto-properties

### ISSUE THREAD

**Issue by drewnoakes** [Fody/Equals#22]
When using `JetBrains.Annotations.dll` to annotate the nullability of fields, generated equality members can avoid performing `null` checks.

A quick scan of [`EqualsInjector.cs`](https://github.com/Fody/Equals/blob/master/Fody/Injectors/EqualsInjector.cs) suggests this doesn't currently happen.

**Comment by SimonCropp** [comment]
are you worried about some impact one performance because of this?

**Comment by drewnoakes** [comment]
Smaller code, fewer branches. Only a small optimisation, admittedly. It'd mean generated code matched that from R#, and was as lean as generated code could be. If you don't think it's worth it, feel free to close this issue.

**Comment by SimonCropp** [comment]
@drewnoakes thanks
