### ISSUE TITLE
HashSet.Contains for object works different than List.Contains for the same collection and same object

### ISSUE THREAD

**Issue by ezavgorodniy** [Fody/Equals#28]
Have console application with this classes: 

    public class SubItem
    {
        public string Content { get; set; }
    }

    public class Item
    {
        public SubItem SubItem1 { get; set; }

        public SubItem SubItem2 { get; set; }
    }

    [Equals]
    public class CompareClass
    {
        public CompareClass()
        {
            Items = new List<Item>();
        }

        [IgnoreDuringEquals]
        public List<Item> Items { get; set; }
    }

    [Equals]
    public class InheritedCompareClass : CompareClass
    {
    }

    public class Program
    {
        static void Main(string[] args)
        {
            var inheritedCompareObject = new InheritedCompareClass();
            var hashSet = new HashSet<CompareClass> { inheritedCompareObject};

            Console.WriteLine(hashSet.Contains(inheritedCompareObject));
            inheritedCompareObject.Items.Add(new Item());
            Console.WriteLine(hashSet.Contains(inheritedCompareObject));
        }
    }

It show me at output

TRUE 
FALSE

If I change the type of inheritedCompareObject to CompareClass it will show me 
TRUE 
TRUE

If I change HashSet to List it will show me 
TRUE 
TRUE

Is it expected?

The idea here is that we change Items property 
      public List<Item> Items { get; set; }

Which is marked with     [IgnoreDuringEquals] attribute

And this impact on HashSet.Contains and as far as I understand it shouldn't

**Comment by rjasica** [comment]
There was a error in detecting IgnoreDuringEquals attribute in base class.
please let me know if new version works for you.

**Comment by ezavgorodniy** [comment]
Yes looks like it fixed now. 

Thanks.
