### ISSUE TITLE
Customize GetHashCode

### ISSUE THREAD

**Issue by SebastianStehle** [Fody/Equals#29]
Feature request: There should be an attribute to customize GetHashCode, similar to CustomEqualsInternal

**Comment by rjasica** [comment]
Great Idea! 
It is ready in 1.6.0 nuget package.

**Comment by SebastianStehle** [comment]
Wow, this was fast. But it is not 100% what I want. Lets say I have a class like this:

	[Equals]
	public class Point
	{
		public int X { get; set; }

		public int Y { get; set; }

		[IgnoreDuringEquals]
		[IgnoreDuringGetHashCode]
		public int Z { get; set; }

		[CustomEqualsInternal]
		private bool CustomLogic(Point other)
		{
			return Z % 10 == other.Z % 10;
		}
		
		[CustomGetHashCodeInternal]
		private int CustomGetHashCode()
		{
			return Z % 10;
		}
	}

What I want is:

	public class Point : IEquatable<Point>
	{
		public int X { get; set; }

		public int Y { get; set; }

		public int Z { get; set; }

		private bool CustomLogic(Point other)
		{
			return Z == other.Z || Z == 0 || other.Z == 0;
		}
		private int CustomGetHashCode()
		{
			return Z % 10;
		}

		public static bool operator ==(Point left, Point right)
		{
			return object.Equals((object)left, (object)right);
		}

		public static bool operator !=(Point left, Point right)
		{
			return !object.Equals((object)left, (object)right);
		}

		private static bool EqualsInternal(Point left, Point right)
		{
			return left.X == right.X && left.Y == right.Y && left.CustomLogic(right);
		}

		public override int GetHashCode()
		{
			return unchecked((this.X.GetHashCode() * 397 ^ this.Y.GetHashCode()) * 397 ^ this.CustomGetHashCode());
		}
	}

**Comment by SebastianStehle** [comment]
If I want full control over the HashCode calculation I should be able to implement GetHashCode by myself. Dont know if this is possible at the moment.

**Comment by rjasica** [comment]
I will change it. Your version is better.

**Comment by SebastianStehle** [comment]
I think you dont need IgnoreDuringGetHashCode, because IgoreDuringEquals makes the same

**Comment by rjasica** [comment]
I released new package. I hope, it will help you.
