### ISSUE TITLE
Support for .NET Standard

### ISSUE THREAD

**Issue by aspnetde** [Fody/Equals#36]
Hi,

Are there any plans to support .NET Standard (currently 1.6), or would a PR be appreciated?

Greetings

Thomas

**Comment by SimonCropp** [comment]
@aspnetde a PR would be appreciated.  for reference https://github.com/Fody/PropertyChanged/ has been changed to support netstandard 1.3

**Comment by SimonCropp** [comment]
@aspnetde sooo about that PR?

**Comment by aspnetde** [comment]
Quite at the bottom of my todo list, at the moment. Not coming anything soon.

**Comment by DamianReeves** [comment]
So @SimonCropp does this mean you are open to a PR that supports moving over to the new VS 2017 csproj, project system?

**Comment by gmarrot** [comment]
Hi,
I opened a pull request (#38) to support .NET Standard 1.0.
