### ISSUE TITLE
Incremental build doesn't work

### ISSUE THREAD

**Issue by johannesegger** [Fody/Equals#39]
I'm getting the following error when building a project that is up-to-date:

> ...\packages\Equals.Fody.1.7.1\build\dotnet\Equals.Fody.targets(13,5): error : Equals expected to be executed. You may need to manually add '\<Equals /\>' into your FodyWeavers.xml. eg <Weavers><Equals/></Weavers>. See https://github.com/Fody/Fody/wiki/SampleUsage

Interestingly I only get that error when I build from the command line using `msbuild Solution.sln`, building from within VS works totally fine.

The responsible part is [here](https://github.com/Fody/Equals/blob/master/NuGet/dotnet.targets#L13). It seems reasonable that the list of executed weavers is empty, if the weavers executed in a previous build, right?

EDIT: I just checked and I can reproduce this in a clean project.
EDIT: It doesn't work with Equals.Fody 1.7.1 and Fody 2.1.1 but it works with Equals.Fody 1.6.2 and Fody 1.29.4

**Comment by SimonCropp** [comment]
can u try v 1.8

**Comment by johannesegger** [comment]
I tried it on a clean project again and it worked, thanks a lot.
