### ISSUE TITLE
Support for fields

### ISSUE THREAD

**Issue by dscopra** [Fody/Equals#41]
Hi,
while validating your tool, I stumbled upon some problems. Once thing is, that IgnoreDuringEquals can not be applied to fields, only to properties. 

Furthermore there is a problem when using Equals on fields. I created a minimal testcase in NUnit, which fails:
```csharp
namespace SomeNamespace
    internal sealed class EqualsTest {
        [Equals]
        internal class SomeClassWithFields {
            public int IntField;

            public SomeClassWithFields(int int_field) {
                IntField = int_field;
            }
        }

        [Test]
        public void Should_Not_Be_Equals() {
            var max = new SomeClassWithFields(int.MaxValue);
            var min = new SomeClassWithFields(int.MinValue);

            Assert.IsFalse(min.Equals(max));
        }
    }
}
```
So my question is, are fields supported or not? 

Used version 1.7.1.

**Comment by SimonCropp** [comment]
currently no. do u want to submit a PR?
