### ISSUE TITLE
Issues after updating to 1.8.0

### ISSUE THREAD

**Issue by milan-stojanovic** [Fody/Equals#43]
After updating Equals.Fody NuGet package from 1.7.1 to 1.8.0 (while using the latest Fody 2.3.3) I've started experiencing issues building projects that use Equals. Specifically, I get the following warning: 

`    Warning: Fody: No configured weavers. It is possible no weavers have been installed or a weaver has been installed into a project type that does not support install.ps1. It may be necessary to manually add that weaver to FodyWeavers.xm;. eg.
<Weavers>
    <WeaverName/>
</Weavers>
see https://github.com/Fody/Fody/wiki/SampleUsage
`

That is because the update overwrote the FodyWeavers.xml file and removed `<Equals />`. If I undo the changes made to the file, I get the following error:

`
    Warning: Fody: No configured weavers. It is possible no weavers have been installed or a weaver has been installed into a project type that does not support install.ps1. It may be necessary to manually add that weaver to FodyWeavers.xm;. eg.
<Weavers>
    <WeaverName/>
</Weavers>
see https://github.com/Fody/Fody/wiki/SampleUsage
`

In any case, I downgraded to 1.7.1 and everything works perfectly (with the latest Fody version).

**Comment by SimonCropp** [comment]
Moving forward will need to manage this file manually
