### ISSUE TITLE
Exceptions during compilation

### ISSUE THREAD

**Issue by ReactiveSoftware** [Fody/Equals#49]
Hi,

I am trying to use the weaver but without success !!!

2>    Fody: Fody (version 3.0.4.0) Executing
2>MSBUILD : error : Fody: An unhandled exception occurred:
2>MSBUILD : error : Exception:
2>MSBUILD : error : Failed to execute weaver C:\Users\Yossef.Cohen\.nuget\packages\equals.fody\1.9.0\netclassicweaver\Equals.Fody.dll
2>MSBUILD : error : Type:
2>MSBUILD : error : System.Exception
2>MSBUILD : error : StackTrace:
2>MSBUILD : error :    at InnerWeaver.ExecuteWeavers()
2>MSBUILD : error :    at InnerWeaver.Execute()
2>MSBUILD : error : Source:
2>MSBUILD : error : FodyIsolated
2>MSBUILD : error : TargetSite:
2>MSBUILD : error : Void ExecuteWeavers()
2>MSBUILD : error : Could not find 'System.CodeDom.Compiler.GeneratedCodeAttribute'.
2>MSBUILD : error : Type:
2>MSBUILD : error : Fody.WeavingException
2>MSBUILD : error : StackTrace:
2>MSBUILD : error :    at TypeCache.FindType(String typeName)
2>MSBUILD : error :    at ModuleWeaver.FindReferences(Func`2 typeFinder)
2>MSBUILD : error :    at ModuleWeaver.Execute()
2>MSBUILD : error :    at InnerWeaver.ExecuteWeavers()
2>MSBUILD : error : Source:
2>MSBUILD : error : FodyHelpers
2>MSBUILD : error : TargetSite:
2>MSBUILD : error : Mono.Cecil.TypeDefinition FindType(System.String)
2>MSBUILD : error : 
2>    Fody:   Finished Fody 48ms.

May this help ?

**Comment by SimonCropp** [comment]
no idea. happy to take a PR that fixes it
