### ISSUE TITLE
Compatibility issue (project .NET classic detected as STANDARD)

### ISSUE THREAD

**Issue by ReactiveSoftware** [Fody/Equals#52]
Hi,

I am using Fody.Equals within a .NET framework (4.7.2) project but have some troubles. It looks like the weaver detects it as a STANDARD. This is the output:

: Fody: An unhandled exception occurred:
1>MSBUILD : error : Exception:
1>MSBUILD : error : Failed to execute weaver C:\Users\Yossef.Cohen\.nuget\packages\equals.fody\1.9.2\build\..\netstandardweaver\Equals.Fody.dll
1>MSBUILD : error : Type:
1>MSBUILD : error : System.Exception
1>MSBUILD : error : StackTrace:
1>MSBUILD : error :    at InnerWeaver.ExecuteWeavers()
1>MSBUILD : error :    at InnerWeaver.Execute()
1>MSBUILD : error : Source:
1>MSBUILD : error : FodyIsolated
1>MSBUILD : error : TargetSite:
1>MSBUILD : error : Void ExecuteWeavers()
1>MSBUILD : error : Could not find 'System.CodeDom.Compiler.GeneratedCodeAttribute'.
1>MSBUILD : error : Type:
1>MSBUILD : error : Fody.WeavingException
1>MSBUILD : error : StackTrace:
1>MSBUILD : error :    at Fody.TypeCache.FindType(String typeName)
1>MSBUILD : error :    at ModuleWeaver.FindReferences(Func`2 typeFinder)
1>MSBUILD : error :    at ModuleWeaver.Execute()
1>MSBUILD : error :    at InnerWeaver.ExecuteWeavers()
1>MSBUILD : error : Source:
1>MSBUILD : error : FodyHelpers
1>MSBUILD : error : TargetSite:
1>MSBUILD : error : Mono.Cecil.TypeDefinition FindType(System.String)
1>MSBUILD : error : 
========== Build: 0 succeeded, 1 failed, 2 up-to-date, 0 skipped ==========

What to do????

Thanks  a lot

**Comment by SimonCropp** [comment]
Please read the issue template
