### ISSUE TITLE
string-arrays not compared as arrays

### ISSUE THREAD

**Issue by greuelpirat** [Fody/Equals#60]
Compiling this class:

    [Equals]
    public class DataClass
    {
        public string String { get; }
        public int[] Ints { get; }
        public string[] Strings { get; }
        public object[] Objects { get; }
    }

results in:

    [DebuggerNonUserCode]
    [GeneratedCode("Equals.Fody", "1.9.3.0")]
    private static bool EqualsInternal(DataClass left, DataClass right)
    {
      return object.Equals((object) left.String, (object) right.String) 
	  && (((object) left != null ? ((object) right != null ? (Helpers.CollectionEquals((IEnumerable) left.Ints, (IEnumerable) right.Ints) ? 1 : 0) : 0) : ((object) right != null ? 0 : 1)) != 0 
	  && object.Equals((object) left.Strings, (object) right.Strings)) 
	  && ((object) left != null ? ((object) right != null ? (Helpers.CollectionEquals((IEnumerable) left.Objects, (IEnumerable) right.Objects) ? 1 : 0) : 0) : ((object) right != null ? 0 : 1)) != 0;
    }

I dont know why string-arrays are not handled as arrays, while the others does.
Using Equals.Fody 1.9.3 and Fody 3.3.5.

Here is my sample solution: [FodyEqualsTest.zip](https://github.com/Fody/Equals/files/2836229/FodyEqualsTest.zip)

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.

**Comment by greuelpirat** [comment]
@SimonCropp did it

**Comment by SimonCropp** [comment]
@greuelpirat can u submit a PR with a failing unit test

**Comment by SimonCropp** [comment]
can u try 1.9.4

**Comment by greuelpirat** [comment]
1.9.4 worked for me. thank you!
